name: doctor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  get: ^4.7.2
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  http: ^1.3.0
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.0.0
  agora_rtc_engine: ^6.5.1
  permission_handler: ^11.4.0
  flutter_callkit_incoming: ^2.5.1
  flutter_ringtone_player: ^4.0.0+4
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/firebase-service-account.json
